ALTER TABLE users ADD COLUMN IF NOT EXISTS us_watch_list_1 TEXT NOT NULL DEFAULT '제목없음';
ALTER TABLE users ADD COLUMN IF NOT EXISTS us_watch_list_2 TEXT NOT NULL DEFAULT '제목없음';
ALTER TABLE users ADD COLUMN IF NOT EXISTS us_watch_list_3 TEXT NOT NULL DEFAULT '제목없음';
ALTER TABLE users ADD COLUMN IF NOT EXISTS us_watch_list_4 TEXT NOT NULL DEFAULT '제목없음';
ALTER TABLE users ADD COLUMN IF NOT EXISTS us_watch_list_5 TEXT NOT NULL DEFAULT '제목없음';
